# Name of workflow
name: Link workflow

# Trigger workflow on all pull requests
on: 
  pull_request:
    branches: 
      -develop


# Jobs to carry out
jobs: 
  test:
    runs-on: mac-os-latest

# Steps in job
steps: 
  - name: github_workflows
    uses: actions/checkout@v1

  - name: Use Node.js